SELECT m.ID, n.FISH_NAME, m.LENGTH
FROM (SELECT i.ID, i.FISH_TYPE, t.LENGTH
FROM FISH_INFO i
JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
FROM FISH_INFO
GROUP BY FISH_TYPE) AS t ON i.FISH_TYPE = t.FISH_TYPE AND i.LENGTH = t.LENGTH) as m
JOIN FISH_NAME_INFO n ON m.FISH_TYPE = n.FISH_TYPE
;